#!/usr/bin/env bash

set -euo pipefail

mode="${1:-all}"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
build_dir="${root}/build/formal"
frama_c="${FRAMA_C:-frama-c}"
e_acsl_gcc="${E_ACSL_GCC:-e-acsl-gcc.sh}"
wp_functions="saves_on,saves_on_with_cover,whc_prove_ap4_against_save2,whc_prove_ap_monotonic,whc_prove_invulnerable_save_caps_ap,whc_prove_cover_does_not_improve_good_save_against_ap0,whc_prove_cover_never_worsens_save"

mkdir -p "${build_dir}"
cd "${root}"

run_parse() {
    "${frama_c}" -quiet -cpp-extra-args=-Iinclude \
        src/calculator.c src/web_api.c src/main.c formal/properties.c
    "${frama_c}" -quiet -cpp-extra-args=-Iinclude \
        src/calculator.c src/web_api.c tests/test_calculator.c
    "${frama_c}" -quiet -cpp-extra-args=-Iinclude \
        src/calculator.c formal/eva_checks.c
    "${frama_c}" -quiet -cpp-extra-args=-Iinclude \
        src/calculator.c formal/runtime_checks.c
}

run_wp() {
    "${frama_c}" -wp -wp-rte -wp-fct "${wp_functions}" -wp-prover alt-ergo \
        -wp-timeout 10 -wp-report-json "${build_dir}/wp.json" \
        -cpp-extra-args=-Iinclude src/calculator.c formal/properties.c \
        >"${build_dir}/wp.log"
    jq -e 'length > 0 and all(.[]; .passed == true and .verdict == "valid")' \
        "${build_dir}/wp.json" >/dev/null
    grep 'Proved goals:' "${build_dir}/wp.log"
}

run_eva() {
    "${frama_c}" -eva -main main -eva-precision 1 \
        -cpp-extra-args='-Iinclude -U__SIZEOF_INT128__' \
        src/calculator.c formal/eva_checks.c >"${build_dir}/eva.log"
    grep '0 alarms generated by the analysis' "${build_dir}/eva.log"
}

run_e_acsl() {
    "${e_acsl_gcc}" -q -c -e '-Iinclude -U__SIZEOF_INT128__' \
        -E '-Iinclude -U__SIZEOF_INT128__' -O "${build_dir}/runtime_checks" \
        src/calculator.c formal/runtime_checks.c >"${build_dir}/e-acsl.log" 2>&1
    "${build_dir}/runtime_checks.e-acsl"
}

case "${mode}" in
    parse) run_parse ;;
    wp) run_wp ;;
    eva) run_eva ;;
    e-acsl) run_e_acsl ;;
    all)
        run_parse
        run_wp
        run_eva
        run_e_acsl
        ;;
    *)
        echo "usage: $0 {parse|wp|eva|e-acsl|all}" >&2
        exit 2
        ;;
esac
