#!/usr/bin/env bash

set -Eeuo pipefail

mode="${1:-all}"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
build_dir="${root}/build/formal"
frama_c="${FRAMA_C:-frama-c}"
e_acsl_gcc="${E_ACSL_GCC:-e-acsl-gcc.sh}"
wp_functions="dice_value_is_valid,probability_distribution_is_normalized,attack_plan_is_valid,saves_on,saves_on_with_cover,modified_roll_threshold,allocate_damage_to_unit,attack_roll_succeeds,whc_prove_ap4_against_save2,whc_prove_ap_monotonic,whc_prove_invulnerable_save_caps_ap,whc_prove_cover_does_not_improve_good_save_against_ap0,whc_prove_cover_never_worsens_save,whc_prove_allocation_respects_unit_capacity,whc_prove_zero_damage_changes_nothing,whc_prove_indirect_low_hit_rolls_fail,whc_prove_roll_modifier_caps,whc_prove_mixed_allocation_respects_capacity,whc_prove_zero_mixed_damage_changes_nothing"

mkdir -p "${build_dir}"
cd "${root}"

dump_logs() {
    for log in "${build_dir}"/*.log; do
        if [[ -f "${log}" ]]; then
            printf '\n==> %s <==\n' "${log}"
            tail -100 "${log}"
        fi
    done
}

trap 'status=$?; dump_logs; exit "${status}"' ERR

run_parse() {
    echo "formal: parse"
    : >"${build_dir}/parse.log"
    "${frama_c}" -quiet -cpp-extra-args=-Iinclude \
        src/calculator.c src/web_api.c src/main.c formal/properties.c \
        >>"${build_dir}/parse.log" 2>&1
    "${frama_c}" -quiet -cpp-extra-args=-Iinclude \
        src/calculator.c src/web_api.c tests/test_calculator.c \
        >>"${build_dir}/parse.log" 2>&1
    "${frama_c}" -quiet -cpp-extra-args=-Iinclude \
        src/calculator.c formal/eva_checks.c \
        >>"${build_dir}/parse.log" 2>&1
    "${frama_c}" -quiet -cpp-extra-args=-Iinclude \
        src/calculator.c formal/runtime_checks.c \
        >>"${build_dir}/parse.log" 2>&1
}

run_wp() {
    echo "formal: wp"
    why3 config detect >/dev/null
    if ! "${frama_c}" -wp -wp-rte -wp-fct "${wp_functions}" -wp-prover alt-ergo \
        -wp-timeout 10 -wp-report-json "${build_dir}/wp.json" \
        -cpp-extra-args=-Iinclude src/calculator.c formal/properties.c \
        >"${build_dir}/wp.log" 2>&1; then
        cat "${build_dir}/wp.log"
        return 1
    fi
    python3 - "${build_dir}/wp.json" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as report:
    goals = json.load(report)
if not goals or not all(goal.get("passed") is True and goal.get("verdict") == "valid" for goal in goals):
    raise SystemExit("Frama-C WP did not validate every proof goal")
PY
    grep 'Proved goals:' "${build_dir}/wp.log"
}

run_eva() {
    echo "formal: eva"
    "${frama_c}" -eva -main main -eva-precision 1 \
        -cpp-extra-args='-Iinclude -U__SIZEOF_INT128__' \
        src/calculator.c formal/eva_checks.c >"${build_dir}/eva.log" 2>&1
    grep '0 alarms generated by the analysis' "${build_dir}/eva.log"
}

run_e_acsl() {
    echo "formal: e-acsl"
    "${e_acsl_gcc}" -q -c -e '-Iinclude -U__SIZEOF_INT128__ -DWHC_E_ACSL' \
        -E '-Iinclude -U__SIZEOF_INT128__ -DWHC_E_ACSL' -O "${build_dir}/runtime_checks" \
        src/calculator.c formal/runtime_checks.c >"${build_dir}/e-acsl.log" 2>&1
    "${build_dir}/runtime_checks.e-acsl"
}

case "${mode}" in
    parse) run_parse ;;
    wp) run_wp ;;
    eva) run_eva ;;
    e-acsl) run_e_acsl ;;
    all)
        run_parse
        run_wp
        run_eva
        run_e_acsl
        ;;
    *)
        echo "usage: $0 {parse|wp|eva|e-acsl|all}" >&2
        exit 2
        ;;
esac
